export const CASE_TEMPLATES = [
  {
    id: "ep_assessment",
    name: "Executive Protection Assessment",
    type: "EP",
    description: "Comprehensive vulnerability assessment for a high-profile individual",
    checklist: [
      "Collect subject identity and aliases",
      "Map all known addresses and transit routes",
      "Enumerate social media accounts and digital footprint",
      "Run breach exposure checks on all known emails",
      "Document behavioral routines and patterns",
      "Identify family members and close associates",
      "Generate Aegis Score baseline",
      "Run Recon Mirror adversarial assessment",
      "Generate Pattern Lens analysis",
      "Export final report for client delivery",
    ],
    suggestedModules: ["profile", "aegis", "recon", "patterns"],
  },
  {
    id: "due_diligence",
    name: "Due Diligence Investigation",
    type: "CI",
    description: "Background verification and risk assessment for business relationships",
    checklist: [
      "Verify subject identity and known aliases",
      "Confirm professional history and organization ties",
      "Check for adverse media and public records",
      "Run breach exposure analysis on known emails",
      "Map corporate affiliations and beneficial ownership",
      "Identify potential conflicts of interest",
      "Generate Aegis Score for risk quantification",
      "Compile findings into client-ready report",
    ],
    suggestedModules: ["profile", "aegis"],
  },
  {
    id: "threat_facility",
    name: "Facility Threat Assessment",
    type: "CT",
    description: "Evaluate threats to a specific location or facility and associated personnel",
    checklist: [
      "Document facility address and surrounding area",
      "Identify key personnel associated with facility",
      "Enumerate digital exposure of facility and staff",
      "Check for data broker listings revealing facility info",
      "Assess behavioral patterns of personnel at facility",
      "Run Recon Mirror with facility-focused scenario",
      "Map associates and known visitors",
      "Generate threat report with recommendations",
    ],
    suggestedModules: ["profile", "aegis", "recon"],
  },
  {
    id: "fraud_investigation",
    name: "Fraud Investigation",
    type: "CI",
    description: "Investigate potential fraud through digital footprint and behavioral analysis",
    checklist: [
      "Collect all known identifiers for subject",
      "Cross-reference email addresses across breaches",
      "Map digital accounts and online personas",
      "Identify inconsistencies in professional claims",
      "Check public records for liens, judgments, filings",
      "Analyze behavioral patterns for deception indicators",
      "Run CrossWire analysis against related subjects",
      "Generate Pattern Lens behavioral assessment",
      "Document evidence chain and export report",
    ],
    suggestedModules: ["profile", "aegis", "patterns", "crosswire"],
  },
  {
    id: "corporate_intel",
    name: "Corporate Intelligence Gathering",
    type: "CI",
    description: "Competitive intelligence and organizational risk mapping",
    checklist: [
      "Identify key executives and decision-makers",
      "Map organizational structure and subsidiaries",
      "Enumerate corporate digital presence",
      "Check for data breaches affecting organization",
      "Analyze public filings and regulatory records",
      "Identify associated entities and partnerships",
      "Run CrossWire to find shared connections",
      "Generate executive briefing report",
    ],
    suggestedModules: ["profile", "aegis", "crosswire"],
  },
];
